### PR TITLE
pastebin added

### PR DESCRIPTION
**Pull request by santosh1994**
@rahulcs  - To run in gh-pages website need to be pushed and currently I'm calling localhost:6969/pasteBin.

It needs to be changed to actual url

### CODE REVIEW

**Comment by rahulcs** [comment]
yeah fix that in both places.

**Comment by santosh1994** [comment]
In node server(Website) Im handling post for /pastebin. So it will be
served in http://www.unbxd.com/pastebin   ??

**Comment by rahulcs** [comment]
@santosh1994 yeah.

**Comment by santosh1994** [comment]
res.setHeader('Access-Control-Allow-Origin', 'http://localhost:9000');

from which origin should I allow "http://unbxd.github.io/" or ?

**Comment by rahulcs** [comment]
yeah for that url itself.

**Pull request closed without merging**
